### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Eastkap** [hungdev/react-customer-chat#1]
Can you confirm this still works? I can't manage to put it into use

**Comment by hungdev** [comment]
@Eastkap yup, it still works. 
I wrote the guide content clearly.
Please note that localhost is not supported.
https://github.com/hungdev/react-customer-chat#note

Try it on https://stackblitz.com/

**Comment by Eastkap** [comment]
All good, seems like it has to be called from the initial app though
